### ISSUE TITLE
Entities in a seperate nuget

### ISSUE THREAD

**Issue by KorsG** [thinktecture/Thinktecture.IdentityServer.v3.EntityFramework#23]
Hi,

I would like to suggest putting Entities in its own project/dll and publish that as a nuget which the core EF project references. 

This will allow us to use the Entities separately in for example our own Entity/Model project without having to introduce Json.net/Automapper/EF as dependencies if we don't want to.

**Comment by johnkors** [comment]
It's of benefit for other backing stores not using EF. 

We're for instance using mongo (yes, we've looked at the idsrv mongodb contrib project btw) and have to copy all the entity classes from the this EF project, or have a dependency on the EF-NuGet including a dependency on EF, which we would prefer not to :)

**Comment by brockallen** [comment]
So I've faced this issue before -- it's really hard building one set of entities that map to both hierarchical and relational stores. See MembershipReboot: https://github.com/brockallen/BrockAllen.MembershipReboot/tree/master/src/BrockAllen.MembershipReboot/Account

**Comment by johnkors** [comment]
I see :/ I guess EF have to do it's "stuff", but for other stores it would be benificial if one could store Client/Token et.al without having to introduce another mapping layer due to non-serializable properties like ClaimsPrincipal. 

Just a thought, but I do understand the hassle involved - so disregard. Not a high priority. :)

**Comment by jnpwly** [comment]
Howdy. I understand that this has already been closed, as @brockallen sees it as being "really hard." I accept this conclusion. I'd just like to echo @johnkors (and also stuff from issue #34): we're not using the EF storage stuff, but am having to duplicate the serialization stuff... 

Not high priority though. :)

**Comment by brockallen** [comment]
Well, EF has all the stupid properties to build the relations. That infects the data structures and that's the real problem, IMO.

**Comment by jnpwly** [comment]
Understood, @brockallen ;)
