### ISSUE TITLE
Entities not being initialized

### ISSUE THREAD

**Issue by danda1man** [thinktecture/Thinktecture.IdentityServer.v3.EntityFramework#30]
I am on the latest release, I cleared my database of the tables to make sure everything would update correctly, but not the entities are not being initialized in the database like they used to when you run the app.  I'm looking through recent commits but not seeing anything that would have cause this right away, something change with the initialization process?

**Comment by brockallen** [comment]
Perhaps you have an entry in the migrations table? That would tell EF that your DB is up to date (regardless of the presence of the tables).

**Comment by danda1man** [comment]
Doh...
