### ISSUE TITLE
Model Names Too long

### ISSUE THREAD

**Issue by LeandroPT** [thinktecture/Thinktecture.IdentityServer.v3.EntityFramework#31]
Hello,

I have updated from beta 3 to beta 4, using oracle RDBMS...
The entity ClientIdentityProviderRestriction exceeds oracle maximum name length of 30 characters.
Can it be shorter? like ClientIdProviderRestriction ?

Thanks

**Comment by brockallen** [comment]
We accept pull requests. 

https://github.com/thinktecture/Thinktecture.IdentityServer.v3.EntityFramework/blob/master/CONTRIBUTING.md

**Comment by brockallen** [comment]
Ok, I was in there making changes today so I made the name shorter.
