### ISSUE TITLE
IdServer APIs and "Lite" classes for serialization

### ISSUE THREAD

**Issue by johnkors** [thinktecture/Thinktecture.IdentityServer.v3.EntityFramework#34]
Hi,

Just a thought - wouldn't it be better that the classes coming from IdentityServer were serializable/"Lite" classes instead of having each *Store-implementer to make their own *Lite-classes like here in EF? 

Is there any reason these Lite-versions of classes could not be moved into IdServer Core?  

We're using another storage mechanism than EF, and hence have to repro what is done here using the different serializer mechanisms.

**Comment by brockallen** [comment]
Sounds related to #23.

**Comment by johnkors** [comment]
Yeah, the EF attributes are a bit annoying in this regard..

**Comment by brockallen** [comment]
I don't see this happening (at least not for RTM), so I'm going to close the issue.
