### ISSUE TITLE
Think about how we deal with schema changes

### ISSUE THREAD

**Issue by brockallen** [thinktecture/Thinktecture.IdentityServer.v3.EntityFramework#5]
Also need to provide a way for a host to specify the Initializer policy. I don't like it in the ServiceFactory ctor.

**Comment by brockallen** [comment]
Ok, I think I've decided that migrations are going to be left to the consuming application to manage. We've tried to do migrations within the project itself and it's been a nightmare. I just tested and a consuming app can easily manage migrations for the DbContexts in IdSvr.Ef's assembly.

**Comment by promontis** [comment]
This is what I would suggest as well :+1:

**Comment by khalidabuhakmeh** [comment]
@brockallen do you have an example of adding a DB migration to the consuming application? When we try to add one it thinks it needs to regenerate the entire schema of our DbContext.
